<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.znq3XXP' shared service.

return $this->privates['.service_locator.znq3XXP'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('data' => function (): \App\Entity\ReceiptInfo {
    return ($this->privates['.errored..service_locator.znq3XXP.App\Entity\ReceiptInfo'] ?? $this->load('getReceiptInfoService.php'));
}));
