<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.fos_user.event_listener' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/Bridge/FosUser/EventListener.php';

return $this->privates['api_platform.fos_user.event_listener'] = new \ApiPlatform\Core\Bridge\FosUser\EventListener(($this->services['fos_user.user_manager'] ?? $this->load('getFosUser_UserManagerService.php')));
