<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Picoss\SonataExtraAdminBundle\Controller\ExtraAdminController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Controller/CRUDController.php';
include_once $this->targetDirs[3].'/vendor/picoss/sonata-extra-admin-bundle/Controller/ExtraAdminController.php';

return $this->services['Picoss\SonataExtraAdminBundle\Controller\ExtraAdminController'] = new \Picoss\SonataExtraAdminBundle\Controller\ExtraAdminController();
