<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_ck_editor.toolbar_manager' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/ToolbarManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/ToolbarManager.php';

$this->privates['fos_ck_editor.toolbar_manager'] = $instance = new \FOS\CKEditorBundle\Model\ToolbarManager();

$instance->setItems(array('full.colors' => array(0 => 'TextColor', 1 => 'BGColor'), 'full.document' => array(0 => 'Source', 1 => '-', 2 => 'Preview', 3 => 'Print'), 'full.insert' => array(0 => 'Image', 1 => 'Table', 2 => 'HorizontalRule', 3 => 'SpecialChar', 4 => 'Smiley', 5 => 'PageBreak')));

return $instance;
