<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_ck_editor.config_manager' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/ConfigManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/ConfigManager.php';

$this->privates['fos_ck_editor.config_manager'] = $instance = new \FOS\CKEditorBundle\Model\ConfigManager();

$instance->setConfigs(array('rip_config' => array('extraPlugins' => 'image2', 'removePlugins' => 'image', 'toolbar' => 'full', 'removeDialogTabs' => 'link:target;link:advanced;image:Link;image:advanced', 'image2_prefillDimensions' => false, 'contentsCss' => 'assets/css/ckeditor_image2.css', 'filebrowserUploadMethod' => 'form', 'filebrowserBrowseRoute' => 'admin_sonata_media_media_ckeditor_browser', 'filebrowserImageBrowseRoute' => 'admin_sonata_media_media_ckeditor_browser', 'filebrowserImageBrowseRouteParameters' => array('provider' => 'sonata.media.provider.image'), 'filebrowserUploadRoute' => 'admin_sonata_media_media_ckeditor_upload', 'filebrowserUploadRouteParameters' => array('provider' => 'sonata.media.provider.file'), 'filebrowserImageUploadRoute' => 'admin_sonata_media_media_ckeditor_upload', 'filebrowserImageUploadRouteParameters' => array('provider' => 'sonata.media.provider.image'))));
$instance->setDefaultConfig('rip_config');

return $instance;
