<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Symfony\Bundle\AclBundle\Command\InitAclCommand' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/acl-bundle/src/Command/InitAclCommand.php';

$this->privates['Symfony\Bundle\AclBundle\Command\InitAclCommand'] = $instance = new \Symfony\Bundle\AclBundle\Command\InitAclCommand(($this->services['doctrine.dbal.default_connection'] ?? $this->load('getDoctrine_Dbal_DefaultConnectionService.php')), ($this->services['security.acl.dbal.schema'] ?? $this->load('getSecurity_Acl_Dbal_SchemaService.php')));

$instance->setName('acl:init');

return $instance;
