<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\OrderSpecial' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/OrderSpecial.php';

return $this->services['App\Controller\OrderSpecial'] = new \App\Controller\OrderSpecial(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')));
