<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'picoss.sonataextraadmin.route.entity' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Builder/RouteBuilderInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Route/PathInfoBuilder.php';
include_once $this->targetDirs[3].'/vendor/picoss/sonata-extra-admin-bundle/Route/EntityRouterBuilder.php';
include_once $this->targetDirs[3].'/vendor/picoss/sonata-extra-admin-bundle/Model/TrashManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/picoss/sonata-extra-admin-bundle/Model/TrashManager.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Model/AuditManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Model/AuditManager.php';

return $this->privates['picoss.sonataextraadmin.route.entity'] = new \Picoss\SonataExtraAdminBundle\Route\EntityRouterBuilder(($this->services['sonata.admin.audit.manager'] ?? $this->services['sonata.admin.audit.manager'] = new \Sonata\AdminBundle\Model\AuditManager($this)), new \Picoss\SonataExtraAdminBundle\Model\TrashManager($this));
