<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'rip.redis.pool' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/cache/Traits/RedisTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/cache/Adapter/RedisAdapter.php';

$this->services['rip.redis.pool'] = $instance = new \Symfony\Component\Cache\Adapter\RedisAdapter(\Symfony\Component\Cache\Adapter\AbstractAdapter::createConnection($this->getEnv('REDIS_URL'), array('lazy' => true)), 'P6eshRMXt0', 0);

$instance->setLogger(($this->privates['monolog.logger.cache'] ?? $this->getMonolog_Logger_CacheService()));

return $instance;
