<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sonata\MediaBundle\Command\SyncThumbsCommand' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Command/ContainerAwareCommand.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/media-bundle/src/Command/BaseCommand.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/media-bundle/src/Command/SyncThumbsCommand.php';

return $this->services['Sonata\MediaBundle\Command\SyncThumbsCommand'] = new \Sonata\MediaBundle\Command\SyncThumbsCommand();
