<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.media.validator.format' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/validator/ConstraintValidatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/validator/ConstraintValidator.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/media-bundle/src/Validator/FormatValidator.php';

return $this->privates['sonata.media.validator.format'] = new \Sonata\MediaBundle\Validator\FormatValidator(($this->services['sonata.media.pool'] ?? $this->getSonata_Media_PoolService()));
