<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.media.serializer.handler.media' shared service.

include_once $this->targetDirs[3].'/vendor/jms/serializer/src/JMS/Serializer/Handler/SubscribingHandlerInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/core-bundle/src/Serializer/SerializerHandlerInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/core-bundle/src/Serializer/BaseSerializerHandler.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/media-bundle/src/Serializer/MediaSerializerHandler.php';

return $this->privates['sonata.media.serializer.handler.media'] = new \Sonata\MediaBundle\Serializer\MediaSerializerHandler(($this->services['sonata.media.manager.media'] ?? $this->getSonata_Media_Manager_MediaService()));
