<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2F9L0e8\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2F9L0e8/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2F9L0e8.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2F9L0e8\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container2F9L0e8\srcDevDebugProjectContainer(array(
    'container.build_hash' => '2F9L0e8',
    'container.build_id' => 'e5508af7',
    'container.build_time' => 1565766454,
), __DIR__.\DIRECTORY_SEPARATOR.'Container2F9L0e8');
