<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7gt.7pH' shared service.

return $this->privates['.service_locator.7gt.7pH'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('sortableHandler' => function () {
    return ($this->privates['picoss.sonataextraadmin.handler.sortable'] ?? $this->load('getPicoss_Sonataextraadmin_Handler_SortableService.php'));
}));
