<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.knSL7mE' shared service.

return $this->privates['.service_locator.knSL7mE'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('data' => function (): \App\Entity\Order {
    return ($this->privates['.errored..service_locator.knSL7mE.App\Entity\Order'] ?? $this->load('getOrderService.php'));
}));
