<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.admin.order' service.

include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Admin/AccessRegistryInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Admin/FieldDescriptionRegistryInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Admin/LifecycleHookProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Admin/MenuBuilderInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Admin/ParentAdminInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Admin/UrlGeneratorInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Admin/AdminInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-acl/Model/DomainObjectInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Admin/AdminTreeInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php';
include_once $this->targetDirs[3].'/src/Admin/OrderAdmin.php';
include_once $this->targetDirs[3].'/src/Admin/OrderBillAdmin.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Security/Handler/SecurityHandlerInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Security/Handler/NoopSecurityHandler.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Translator/LabelTranslatorStrategyInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Translator/NativeLabelTranslatorStrategy.php';

$this->factories['app.admin.order'] = function () {
    $instance = new \App\Admin\OrderAdmin('app.admin.order', 'App\\Entity\\Order', 'Sonata\\AdminBundle\\Controller\\CRUDController');

    $a = new \App\Admin\OrderBillAdmin('app.admin.order_bill', 'App\\Entity\\OrderBill', 'Sonata\\AdminBundle\\Controller\\CRUDController');
    $b = ($this->services['sonata.admin.manager.orm'] ?? $this->load('getSonata_Admin_Manager_OrmService.php'));
    $c = ($this->privates['sonata.admin.builder.orm_form'] ?? $this->load('getSonata_Admin_Builder_OrmFormService.php'));
    $d = ($this->privates['sonata.admin.builder.orm_show'] ?? $this->load('getSonata_Admin_Builder_OrmShowService.php'));
    $e = ($this->privates['sonata.admin.builder.orm_list'] ?? $this->load('getSonata_Admin_Builder_OrmListService.php'));
    $f = ($this->privates['sonata.admin.builder.orm_datagrid'] ?? $this->load('getSonata_Admin_Builder_OrmDatagridService.php'));
    $g = ($this->services['translator'] ?? $this->getTranslatorService());
    $h = ($this->services['sonata.admin.pool'] ?? $this->getSonata_Admin_PoolService());
    $i = ($this->services['sonata.admin.route.default_generator'] ?? $this->load('getSonata_Admin_Route_DefaultGeneratorService.php'));
    $j = ($this->services['validator'] ?? $this->getValidatorService());
    $k = ($this->privates['sonata.admin.security.handler.noop'] ?? $this->privates['sonata.admin.security.handler.noop'] = new \Sonata\AdminBundle\Security\Handler\NoopSecurityHandler());
    $l = ($this->services['knp_menu.factory'] ?? $this->load('getKnpMenu_FactoryService.php'));
    $m = ($this->services['sonata.admin.route.path_info'] ?? $this->load('getSonata_Admin_Route_PathInfoService.php'));
    $n = ($this->services['sonata.admin.label.strategy.native'] ?? $this->services['sonata.admin.label.strategy.native'] = new \Sonata\AdminBundle\Translator\NativeLabelTranslatorStrategy());
    $o = ($this->services['sonata.admin.event.extension'] ?? $this->load('getSonata_Admin_Event_ExtensionService.php'));
    $p = ($this->privates['picoss.sonataextraadmin.route.entity'] ?? $this->load('getPicoss_Sonataextraadmin_Route_EntityService.php'));

    $a->setManagerType('orm');
    $a->setModelManager($b);
    $a->setFormContractor($c);
    $a->setShowBuilder($d);
    $a->setListBuilder($e);
    $a->setDatagridBuilder($f);
    $a->setTranslator($g, false);
    $a->setConfigurationPool($h);
    $a->setRouteGenerator($i);
    $a->setValidator($j);
    $a->setSecurityHandler($k);
    $a->setMenuFactory($l);
    $a->setRouteBuilder($m);
    $a->setLabelTranslatorStrategy($n);
    $a->setPagerType('default');
    $a->setLabel('OrderBillAdmin');
    $a->showMosaicButton(false);
    $a->setTemplateRegistry(($this->services['app.admin.order_bill.template_registry'] ?? $this->load('getApp_Admin_OrderBill_TemplateRegistryService.php')));
    $a->setSecurityInformation(array());
    $a->initialize();
    $a->addExtension($o);
    $a->setFormTheme(array(0 => '@SonataDoctrineORMAdmin/Form/form_admin_fields.html.twig'));
    $a->setFilterTheme(array(0 => '@SonataDoctrineORMAdmin/Form/filter_admin_fields.html.twig'));
    $a->setTemplate('history', '@PicossSonataExtraAdmin/CRUD/history.html.twig');
    $a->setTemplate('history_revert', '@PicossSonataExtraAdmin/CRUD/history_revert.html.twig');
    $a->setTemplate('history_revision_timestamp', '@PicossSonataExtraAdmin/CRUD/history_revision_timestamp.html.twig');
    $a->setTemplate('trash', '@PicossSonataExtraAdmin/CRUD/trash.html.twig');
    $a->setTemplate('untrash', '@PicossSonataExtraAdmin/CRUD/untrash.html.twig');
    $a->setTemplate('inner_trash_list_row', '@PicossSonataExtraAdmin/CRUD/list_trash_inner_row.html.twig');
    $a->setTemplate('button_trash', '@PicossSonataExtraAdmin/Button/trash_button.html.twig');
    $a->setRouteBuilder($p);

    $instance->addChild($a, 'order_info');
    $instance->setWechatPayRefund(($this->privates['rip.wechat.pay_refund'] ?? $this->load('getRip_Wechat_PayRefundService.php')));
    $instance->setManagerType('orm');
    $instance->setModelManager($b);
    $instance->setFormContractor($c);
    $instance->setShowBuilder($d);
    $instance->setListBuilder($e);
    $instance->setDatagridBuilder($f);
    $instance->setTranslator($g, false);
    $instance->setConfigurationPool($h);
    $instance->setRouteGenerator($i);
    $instance->setValidator($j);
    $instance->setSecurityHandler($k);
    $instance->setMenuFactory($l);
    $instance->setRouteBuilder($m);
    $instance->setLabelTranslatorStrategy($n);
    $instance->setPagerType('default');
    $instance->setLabel('OrderAdmin');
    $instance->showMosaicButton(false);
    $instance->setTemplateRegistry(($this->services['app.admin.order.template_registry'] ?? $this->load('getApp_Admin_Order_TemplateRegistryService.php')));
    $instance->setSecurityInformation(array());
    $instance->initialize();
    $instance->addExtension($o);
    $instance->setFormTheme(array(0 => '@SonataDoctrineORMAdmin/Form/form_admin_fields.html.twig'));
    $instance->setFilterTheme(array(0 => '@SonataDoctrineORMAdmin/Form/filter_admin_fields.html.twig'));
    $instance->setTemplate('history', '@PicossSonataExtraAdmin/CRUD/history.html.twig');
    $instance->setTemplate('history_revert', '@PicossSonataExtraAdmin/CRUD/history_revert.html.twig');
    $instance->setTemplate('history_revision_timestamp', '@PicossSonataExtraAdmin/CRUD/history_revision_timestamp.html.twig');
    $instance->setTemplate('trash', '@PicossSonataExtraAdmin/CRUD/trash.html.twig');
    $instance->setTemplate('untrash', '@PicossSonataExtraAdmin/CRUD/untrash.html.twig');
    $instance->setTemplate('inner_trash_list_row', '@PicossSonataExtraAdmin/CRUD/list_trash_inner_row.html.twig');
    $instance->setTemplate('button_trash', '@PicossSonataExtraAdmin/Button/trash_button.html.twig');
    $instance->setRouteBuilder($p);

    return $instance;
};

return $this->factories['app.admin.order']();
