<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Fresh\DoctrineEnumBundle\Form\EnumTypeGuesser' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeGuesserInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/doctrine-bridge/Form/DoctrineOrmTypeGuesser.php';
include_once $this->targetDirs[3].'/vendor/fresh/doctrine-enum-bundle/Form/EnumTypeGuesser.php';

return $this->privates['Fresh\DoctrineEnumBundle\Form\EnumTypeGuesser'] = new \Fresh\DoctrineEnumBundle\Form\EnumTypeGuesser(($this->services['doctrine'] ?? $this->getDoctrineService()), $this->parameters['doctrine.dbal.connection_factory.types']);
