<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_ck_editor.plugin_manager' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/PluginManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/PluginManager.php';

$this->privates['fos_ck_editor.plugin_manager'] = $instance = new \FOS\CKEditorBundle\Model\PluginManager();

$instance->setPlugins(array('image2' => array('path' => '/vendor/ckeditor/plugin/image2/', 'filename' => 'plugin.js')));

return $instance;
