<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_ck_editor.form.type' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Form/Type/CKEditorType.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/StylesSetManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/StylesSetManager.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/TemplateManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/TemplateManager.php';

$this->privates['fos_ck_editor.form.type'] = $instance = new \FOS\CKEditorBundle\Form\Type\CKEditorType(($this->privates['fos_ck_editor.config_manager'] ?? $this->load('getFosCkEditor_ConfigManagerService.php')), ($this->privates['fos_ck_editor.plugin_manager'] ?? $this->load('getFosCkEditor_PluginManagerService.php')), ($this->privates['fos_ck_editor.styles_set_manager'] ?? $this->privates['fos_ck_editor.styles_set_manager'] = new \FOS\CKEditorBundle\Model\StylesSetManager()), ($this->privates['fos_ck_editor.template_manager'] ?? $this->privates['fos_ck_editor.template_manager'] = new \FOS\CKEditorBundle\Model\TemplateManager()), ($this->privates['fos_ck_editor.toolbar_manager'] ?? $this->load('getFosCkEditor_ToolbarManagerService.php')));

$instance->isInputSync(true);

return $instance;
