<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventSubscriber\MemberPaySubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/EventSubscriber/MemberPaySubscriber.php';

return $this->privates['App\EventSubscriber\MemberPaySubscriber'] = new \App\EventSubscriber\MemberPaySubscriber(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
