<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.uOx5GXH.Sonata\AdminBundle\Datagrid\ProxyQueryInterface' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.uOx5GXH": it references interface "Sonata\\AdminBundle\\Datagrid\\ProxyQueryInterface" but no such service exists. Did you create a class that implements this interface?');
