<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.media.formatter.twig' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/media-bundle/src/Twig/Extension/FormatterMediaExtension.php';

return $this->services['sonata.media.formatter.twig'] = new \Sonata\MediaBundle\Twig\Extension\FormatterMediaExtension(($this->privates['sonata.media.twig.extension'] ?? $this->getSonata_Media_Twig_ExtensionService()));
