<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.admin.route_loader' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/config/Loader/LoaderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/config/Loader/Loader.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Route/AdminPoolLoader.php';

return $this->services['sonata.admin.route_loader'] = new \Sonata\AdminBundle\Route\AdminPoolLoader(($this->services['sonata.admin.pool'] ?? $this->getSonata_Admin_PoolService()), array(0 => 'app.admin.banner', 1 => 'app.admin.goods', 2 => 'app.admin.classify_goods', 3 => 'app.admin.goods_banner', 4 => 'app.admin.marketing', 5 => 'app.admin.custom_page', 6 => 'app.admin.consumer', 7 => 'app.admin.receipt_infos', 8 => 'app.admin.order', 9 => 'app.admin.order_bill', 10 => 'sonata.media.admin.media', 11 => 'sonata.media.admin.gallery', 12 => 'sonata.media.admin.gallery_has_media', 13 => 'sonata.user.admin.user', 14 => 'sonata.user.admin.group'), $this);
