<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.NVX3a_c.Picoss\SonataExtraAdminBundle\Model\TrashManager' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.NVX3a_c": it references class "Picoss\\SonataExtraAdminBundle\\Model\\TrashManager" but no such service exists. You should maybe alias this class to the existing "picoss.sonataextraadmin.trash.manager" service.');
