<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.uOx5GXH' shared service.

return $this->privates['.service_locator.uOx5GXH'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('query' => function (): \Sonata\AdminBundle\Datagrid\ProxyQueryInterface {
    return ($this->privates['.errored..service_locator.uOx5GXH.Sonata\AdminBundle\Datagrid\ProxyQueryInterface'] ?? $this->load('getProxyQueryInterfaceService.php'));
}));
