<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_ck_editor.templating.helper' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Templating/CKEditorHelper.php';

return $this->privates['fos_ck_editor.templating.helper'] = new \FOS\CKEditorBundle\Templating\CKEditorHelper(($this->privates['fos_ck_editor.renderer'] ?? $this->getFosCkEditor_RendererService()));
