<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'rip.wechat.pay_refund' shared autowired service.

include_once $this->targetDirs[3].'/src/DependencyInjection/WechatPayRefund.php';

return $this->privates['rip.wechat.pay_refund'] = new \App\DependencyInjection\WechatPayRefund($this->parameters['rip.payment'], $this->parameters['rip.refund'], ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
