<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.user.form.gender_list' shared service.

@trigger_error('The "sonata.user.form.gender_list" service is deprecated since 4.1 and will be removed in 5.0.', E_USER_DEPRECATED);

return $this->privates['sonata.user.form.gender_list'] = new \Sonata\UserBundle\Form\Type\UserGenderListType('App\\Application\\Sonata\\UserBundle\\Entity\\User', 'getGenderList', 'Sonata\\UserBundle\\Form\\Type\\UserGenderListType');
