<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.acl.object_identity_retrieval_strategy' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security-acl/Model/ObjectIdentityRetrievalStrategyInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-acl/Domain/ObjectIdentityRetrievalStrategy.php';

return $this->privates['security.acl.object_identity_retrieval_strategy'] = new \Symfony\Component\Security\Acl\Domain\ObjectIdentityRetrievalStrategy();
