<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'templating.helper.markdown' shared service.

include_once $this->targetDirs[3].'/vendor/knplabs/knp-markdown-bundle/Helper/MarkdownHelper.php';

return $this->privates['templating.helper.markdown'] = new \Knp\Bundle\MarkdownBundle\Helper\MarkdownHelper(($this->privates['markdown.parser.parser_manager'] ?? $this->getMarkdown_Parser_ParserManagerService()));
