<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\DependencyInjection\WechatPrePayIdStorage' shared autowired service.

include_once $this->targetDirs[3].'/src/DependencyInjection/WechatPrePayIdStorage.php';

return $this->privates['App\DependencyInjection\WechatPrePayIdStorage'] = new \App\DependencyInjection\WechatPrePayIdStorage(($this->services['rip.redis.pool'] ?? $this->getRip_Redis_PoolService()));
