<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventSubscriber\WechatPayRefundSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/EventSubscriber/WechatPayRefundSubscriber.php';

return $this->privates['App\EventSubscriber\WechatPayRefundSubscriber'] = new \App\EventSubscriber\WechatPayRefundSubscriber(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()), ($this->privates['App\DependencyInjection\WechatPrePayIdStorage'] ?? $this->load('getWechatPrePayIdStorageService.php')));
