<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Goods extends \App\Entity\Goods implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'stock', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'classify', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'describes', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'market_price', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'deposit_price', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'long_size', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'wide_size', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'details', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'pictures', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'orderBill', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'updated_at', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'file'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'stock', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'classify', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'describes', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'market_price', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'deposit_price', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'long_size', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'wide_size', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'details', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'pictures', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'orderBill', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'updated_at', '' . "\0" . 'App\\Entity\\Goods' . "\0" . 'file'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Goods $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getStock(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStock', []);

        return parent::getStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setStock(int $stock): \App\Entity\Goods
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStock', [$stock]);

        return parent::setStock($stock);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(string $image): \App\Entity\Goods
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassify(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassify', []);

        return parent::getClassify();
    }

    /**
     * {@inheritDoc}
     */
    public function addClassify(\App\Entity\ClassifyGoods $classify): \App\Entity\Goods
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addClassify', [$classify]);

        return parent::addClassify($classify);
    }

    /**
     * {@inheritDoc}
     */
    public function removeClassify(\App\Entity\ClassifyGoods $classify): \App\Entity\Goods
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeClassify', [$classify]);

        return parent::removeClassify($classify);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescribes(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescribes', []);

        return parent::getDescribes();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescribes(?string $describes): \App\Entity\Goods
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescribes', [$describes]);

        return parent::setDescribes($describes);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarketPrice(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarketPrice', []);

        return parent::getMarketPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarketPrice(float $market_price): \App\Entity\Goods
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarketPrice', [$market_price]);

        return parent::setMarketPrice($market_price);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepositPrice(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepositPrice', []);

        return parent::getDepositPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepositPrice(float $deposit_price): \App\Entity\Goods
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepositPrice', [$deposit_price]);

        return parent::setDepositPrice($deposit_price);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongSize(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongSize', []);

        return parent::getLongSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongSize(int $long_size): \App\Entity\Goods
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongSize', [$long_size]);

        return parent::setLongSize($long_size);
    }

    /**
     * {@inheritDoc}
     */
    public function getWideSize(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWideSize', []);

        return parent::getWideSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setWideSize(int $wide_size): \App\Entity\Goods
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWideSize', [$wide_size]);

        return parent::setWideSize($wide_size);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetails(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetails', []);

        return parent::getDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function setDetails(?string $details): \App\Entity\Goods
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetails', [$details]);

        return parent::setDetails($details);
    }

    /**
     * {@inheritDoc}
     */
    public function getPictures(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPictures', []);

        return parent::getPictures();
    }

    /**
     * {@inheritDoc}
     */
    public function addPicture(\App\Entity\GoodsBanner $picture): \App\Entity\Goods
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPicture', [$picture]);

        return parent::addPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function removePicture(\App\Entity\GoodsBanner $picture): \App\Entity\Goods
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePicture', [$picture]);

        return parent::removePicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderBill(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderBill', []);

        return parent::getOrderBill();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderBill(\App\Entity\OrderBill $orderBill): \App\Entity\Goods
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderBill', [$orderBill]);

        return parent::addOrderBill($orderBill);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrderBill(\App\Entity\OrderBill $orderBill): \App\Entity\Goods
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrderBill', [$orderBill]);

        return parent::removeOrderBill($orderBill);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalBill()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalBill', []);

        return parent::getTotalBill();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Goods
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(?\DateTimeInterface $created_at): \App\Entity\Goods
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeInterface $updated_at): \App\Entity\Goods
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updated_at]);

        return parent::setUpdatedAt($updated_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        return parent::setFile($file);
    }

}
