<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Marketing extends \App\Entity\Marketing implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'explain_text', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'original_price', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'present_price', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'discount', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'validity_date', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'members', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'deleted_at', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'updated_at', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'file'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'explain_text', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'original_price', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'present_price', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'discount', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'validity_date', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'members', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'deleted_at', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'updated_at', '' . "\0" . 'App\\Entity\\Marketing' . "\0" . 'file'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Marketing $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(string $image): \App\Entity\Marketing
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Marketing
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getExplainText(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExplainText', []);

        return parent::getExplainText();
    }

    /**
     * {@inheritDoc}
     */
    public function setExplainText(string $explain_text): \App\Entity\Marketing
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExplainText', [$explain_text]);

        return parent::setExplainText($explain_text);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginalPrice(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginalPrice', []);

        return parent::getOriginalPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginalPrice(float $original_price): \App\Entity\Marketing
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginalPrice', [$original_price]);

        return parent::setOriginalPrice($original_price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPresentPrice(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresentPrice', []);

        return parent::getPresentPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPresentPrice(float $present_price): \App\Entity\Marketing
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPresentPrice', [$present_price]);

        return parent::setPresentPrice($present_price);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscount(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscount', []);

        return parent::getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscount(float $discount): \App\Entity\Marketing
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscount', [$discount]);

        return parent::setDiscount($discount);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidityDate(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidityDate', []);

        return parent::getValidityDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidityDate(int $validity_date): \App\Entity\Marketing
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidityDate', [$validity_date]);

        return parent::setValidityDate($validity_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getMembers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMembers', []);

        return parent::getMembers();
    }

    /**
     * {@inheritDoc}
     */
    public function addMember(\App\Entity\Member $member): \App\Entity\Marketing
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMember', [$member]);

        return parent::addMember($member);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMember(\App\Entity\Member $member): \App\Entity\Marketing
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMember', [$member]);

        return parent::removeMember($member);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', []);

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt(\DateTimeInterface $deleted_at): \App\Entity\Marketing
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', [$deleted_at]);

        return parent::setDeletedAt($deleted_at);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(?\DateTimeInterface $created_at): \App\Entity\Marketing
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeInterface $updated_at): \App\Entity\Marketing
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updated_at]);

        return parent::setUpdatedAt($updated_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        return parent::setFile($file);
    }

}
